### ISSUE TITLE
Unable to access bns.prussia.dev

### ISSUE THREAD

**Issue by elementalennui-dev** [stjet/bns#2]
Error in Chrome:

bns.prussia.dev normally uses encryption to protect your information. When Chrome tried to connect to bns.prussia.dev this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be bns.prussia.dev, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit bns.prussia.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by stjet** [comment]
No need to open an issue for this. Just github pages being github pages.
